=== JomiXedYu/Pulsar/Pulsar/Packages/Engine/Shaders/ShaderSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type":"object",
    "properties": {
        "CullMode" : {
            "type":"string",
            "enum": ["None",  "Front", "Back", "FrontAndBack"]
        },
        "DepthTestEnable" : {
            "type":"boolean"
        },
        "DepthWriteEnable": {
            "type":"boolean"
        },
        "DepthCompareOp": {
            "type":"string",
            "enum": ["Never", "Less", "Equal", "LessOrEqual", "Greater", "NotEqual", "GreaterOrEqual", "Always"]
        },
        "StencilTestEnable": {
            "type":"boolean"
        },
        "RenderingType": {
            "type":"string",
            "enum": ["OpaqueForward", "OpaqueDeferred", "Transparency", "PostProcessing"]
        },
        "ConstantProperties": {
            "type":"array",
            "items": {
                "type":"object",
                "properties": {
                    "Name": {
                        "type":"string"
                    },
                    "Type": {
                        "type":"string",
                        "enum": ["IntScalar", "Scalar", "Vector"]
                    },
                    "Value": {
                        "type":"string"
                    }
                }
            }
        },
        "Properties": {
            "type":"array",
            "items": {
                "type":"object",
                "properties": {
                    "Name": {
                        "type":"string"
                    },
                    "Type": {
                        "type":"string",
                        "enum": ["Texture2D"]
                    }
                }
            }
        },
        "Features" : {
            "type":"array",
            "items": {
                "type":"object",
                "properties": {
                    "Name": {
                        "type":"string"
                    },
                    "Default" : {
                        "type":"boolean"
                    }
                }
            }
        }
    }
}

=== JomiXedYu/Pulsar/Pulsar/Packages/Engine/Shaders/ImagePreview.sh.json
{
  "CullMode": "Back",
  "DepthTestEnable": false,
  "DepthWriteEnable": false,
  "DepthCompareOp": "Less",
  "StencilTestEnable": false,
  "RenderingType": "PostProcessing",
  "ConstantProperties": [
    {
      "Name": "_CheckerColorA",
      "Type": "Vector",
      "Value": "0.99, 0.99, 0.99, 1"
    },
    {
      "Name": "_CheckerColorB",
      "Type": "Vector",
      "Value": "0.75, 0.75, 0.75, 1"
    },
    {
      "Name": "_GridSize",
      "Type": "Scalar",
      "Value": "10"
    },
    {
      "Name": "_Flags",
      "Type": "IntScalar",
      "Value": "-1"
    }
  ],
  "Properties" : [
    {
      "Name": "_Image",
      "Type": "Texture2D",
      "Value": "WHITE"
    }
  ]
}
